title: My First Blog.
author: Hrishikesh D S
email: dshrishikesh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Heya this is Hrishikesh and this is my first blog

# social links

github_username:  Hrishikesh-DS

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
